development:  
  adapter: postgresql
  encoding: unicode 
  pool: 5
  database: trblog_development 
  username: pguser  
  password: root  
  host: localhost 
  port: 5432


# test:
#   <<: *default
#   database: trblog_test


# production:
#   <<: *default
#   database: trblog_production
#   username: trblog
#   password: <%= ENV['TRBLOG_DATABASE_PASSWORD'] %>
